# Changes here will be overwritten by Copier
_commit: '0.1'
_src_path: https://github.com/sandeeps311/copier_minimal_example.git
author_email: null
author_fullname: null
author_username: null
copyright_date: '2021'
copyright_holder: None
copyright_holder_email: None
copyright_license: ISC License
project_description: testdesc
project_name: test
python_package_command_line_name: test
python_package_distribution_name: test
python_package_import_name: test
repository_name: test
repository_namespace: None
repository_provider: github.com
use_precommit: true

